language: python

cache:
  directories:
  - ~/.cache/pip
  - ~/.pyenv

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: linux
          python: 3.2
          env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0"
        - os: linux
          python: 3.3
          env: TOXENV=py33
        - os: linux
          python: 3.4
          env: TOXENV=py34
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.5-dev
          env: TOXENV=py35
        - os: linux
          python: nightly
          env: TOXENV=py36
        - os: linux
          python: 3.4
          env: TOXENV=docs
        - os: linux
          python: 2.7
          env: TOXENV=pep8
        - os: linux
          python: 3.4
          env: TOXENV=pep8
        - os: linux
          python: 3.4
          env:
            - TOXENV=packaging
            - PYPIUSER=grzanka
            #  pypi secured password (PYPIPASS variable), you need to update it to your own if you want to use it
            - secure: "PUKOSRVf18nKaBakGxw/ch/n6MB10nRrmNkZKfezThO/nTczyDPSM+jtKVjt06tJFd3D1qIWwX4mOn9I5Y6qSvGGSOU6s8LzlWw6ss7AZKISy+dSOVM3ilb0gaTdIiSCUoX9zWThkOH+1L9c5QQ4BtPxyVQgGMpAE55zCmfCujTNW32rOU+KW40ArKe0o/v0x7mox3nzxqnc7tNk0It3NKD2K+JgR/JVR7Hc9UyVSpm3zZkUu2RR1G/4Mc1XilWzlmPFdEa6P7fyPzNfcmI3GGJiuiVoIv90LSJUyPCmQqweEHv4liEwGX5K7TpvPuWE1GH4R5aDLmX4hQFp8wBg2aAuoZ6hElET1Nw+QROyl2+EuGHRsvWDpdJTzAUfIA+lGb26A2OsLatP40IjDbPQkouUdJoh1yZ1UnbKKmiG+d/sDb+C2/kBnQN9rc3NxYMaA3Wo/hE+o8mcYeVtUo14JkPJYTTo70Pq9ZkI3K8tAutdRdTf2ocT16iLux9nkS5+lumaj++vgE9zzM0E12RSbz8w8czWxm0+GD3p3BkZFvdvWiaRm3gxpgvSqnC04AWd5c+Gp3FI6zf3SSpOOGJxy6fLw9jBLzWocb4h5BfVwQntbCSlOLqCYBDYtd/eAde1cC+nbDp7Icujcm4eLgZ5Xqs+PxXeGjgf3gW/TE11yFw="
            - PYPITESTUSER=grzanka
        - os: osx
          language: generic
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=py34
        - os: osx
          language: generic
          env: TOXENV=py33
        - os: osx
          language: generic
          env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0"
        - os: osx
          language: generic
          env: TOXENV=py27
#    uncomment and adjust if you want to allow some failures
#    allow_failures:
#        - os: osx
#          language: generic
#          env: TOXENV=py27

# travis-ci runs by default on ancient Ubuntu 12.04 (precise)
# following options will give us Ubuntu 14.04 (trusty)
sudo: required
dist: trusty

before_install:
  - PYTHON_VERSION="py3"
  - if [[ $TOXENV == "py27" ]]; then PYTHON_VERSION="py2" ; fi
  - bash ./install_deps.sh $PYTHON_VERSION

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then travis_wait bash ./.travis/install_linux.sh ; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then travis_wait 60 bash ./.travis/install_osx.sh ; fi

# if scipy is used, then installation from pip last longer than 10min, thus we add travis_wait
script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then travis_wait tox --notest && tox -- -n 8 ; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then travis_wait bash ./.travis/run_osx.sh ; fi

after_success:
  # deploy to normal if tag is present
  - if [[ $TRAVIS_TAG != "" ]] && [[ $TOXENV == "packaging" ]]; then bash .travis/deploy_package.sh pypi ; fi

notifications:
  email:
    - leszek.grzanka@gmail.com
