[build-system]
requires = ["scikit-build-core>0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "pyamtrack"
version = "0.1.0"
description = "Python bindings for libamtrack"
readme = "README.md"
authors = [{ name = "Your Name", email = "your.email@example.com" }]
requires-python = ">=3.9"
license = { file = "LICENSE" }
#dependencies = ["numpy"]

[tool.scikit-build]
wheel.expand-macos-universal-tags = true
minimum-version = "build-system.requires"

[tool.cibuildwheel.linux]
before-all = "./scripts/build_gsl.sh"
build = "cp311-manylinux* cp312-manylinux* cp313-manylinux*"
archs = ["auto64"]