name: Linux Build & Test

on:
  workflow_call:
    # (Add inputs if needed later)

jobs:
  build_and_test_linux:
    runs-on: ubuntu-latest
    outputs:
      linux_status: ${{ job.status }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system packages
        run: sudo apt-get install -y --no-install-recommends libgsl-dev python3-pip

      - name: Install Python dependencies
        run: pip install --upgrade build

      - name: Build & Install pyamtrack (Linux)
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ runner.temp }}/usr"
          cmake --build . --parallel
          cmake --install .

      - name: Build Python Wheel
        run: python -m build

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libamtrack-linux
          path: |
            ${{ runner.temp }}/usr/
            dist/*.whl
          if-no-files-found: error
          retention-days: 5