name: CI Pipeline
permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    tags: ['v*']
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build_and_test_linux:
    name: Linux Build & Test
    uses: ./.github/workflows/linux-reusable.yml

  build_and_test_macos:
    name: macOS Build & Test
    needs: build_and_test_linux
    if: ${{ needs.build_and_test_linux.result == 'success' }}
    uses: ./.github/workflows/macos-reusable.yml
    with:
      linux_status: ${{ needs.build_and_test_linux.result }}
